#!/usr/bin/env node
let compiler = require('surplus/compiler');
let fs = require('fs');
let path = require('path');

function build(file) {
  console.log('build', file);
  const input = fs.readFileSync(file).toString();
  const jsxFilename = path.basename(file);
  const jsFilename = jsxFilename.replace(/\.jsx$/, '.js');
  const { src, map } = compiler.compile(input, { sourcemap: 'extract' });
  map.file = jsFilename;
  map.sources = [jsxFilename];
  fs.writeFileSync(file.replace(/\.jsx$/, '.js'), src);
  fs.writeFileSync(file.replace(/\.jsx$/, '.js.map'), JSON.stringify(map));
}

function scan(dir) {
  let files = fs.readdirSync(dir);
  files.forEach(file => {
    if (file.endsWith('.jsx')) {
      build(path.join(dir, file));
    }
  });
}

scan('src');
scan('demo')
