#!/bin/bash
set -e
set -o pipefail

npm run build:demo
npx webpack --mode=production demo/demo.js
rm -rf www
mkdir www
cp -r dist www
cp demo.html www/index.html
surge www https://s-json-demo.surge.sh
